### ISSUE TITLE
Black screen, no errors

### ISSUE THREAD

**Issue by ghost** [borjanebbal/webrtc-node-app#2]
Hello, when i start a call, and use another device to connect to the same call, there is a black screen, and any error in the console.
Can you help me ?
Thank 😉

**Comment by borjanebbal** [comment]
Hi! There may be many reasons why you get that error, please check that your browser supports WebRTC, that you're using HTTPS and that you're sharing your local server properly (I recommended [ngrok](https://ngrok.com/) as a tunnelling service in the article but there are many others you can use). 

Please let me know if that works.

**Comment by viniciusbitten** [comment]
I am having the same issue. It shows my camera, but the other user's camera image is always all black. In the console, it always says that a new room was created. When I put the ID of a previously created, still open room, it creates a new one again, instead of joining. I'm using ngrok and https... Do you have any idea on this?

**Comment by borjanebbal** [comment]
I'm afraid I would need to play with your devices to find what's wrong. I have run the server with Nodemon and everything works fine connecting my laptop and my phone. These are my server logs:

![image](https://user-images.githubusercontent.com/50955457/107857234-85110180-6e2d-11eb-845a-157dcee7ca28.png)

**Comment by subodhghulaxe** [comment]
I also faced the same issue, fixed it by removing latest socket.io and installing socket.io@2.4.0

`io.sockets.adapter.rooms[roomId]` is not working with 3.x version of socket.io
